export const TEXT_CHANGE = 'TEXT_CHANGE';
export const TEXT_BLURRED = 'TEXT_BLURRED';
export const SLIDER_CHANGE = 'SLIDER_CHANGE';
export const LICENSE_CHANGE = 'LICENSE_CHANGE';
export const TOGGLE_FORKED = 'TOGGLE_FORKED';
export const GET_REPOS = 'GET_REPOS';
export const REPOS_SUCCESS = 'REPOS_SUCCESS';
export const REPOS_FAILURE = 'REPOS_FAILURE';

export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_TOTAL_COUNT = 'UPDATE_TOTAL_COUNT';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_PAGE_OF_RESULTS = 'UPDATE_PAGE_OF_RESULTS';
export const UPDATE_PAGER = 'UPDATE_PAGER';

export const SET_PAGER = 'SET_PAGER';
export const CHANGE_PAGE = 'CHANGE_PAGE';
